### ISSUE TITLE
nodes draining

### ISSUE THREAD

**Issue by kryczko** [ai4d-iasc/trixie#35]
There are 9 nodes that are draining and 2 job testing nodes that are drained.

**Comment by ddamoursNRC** [comment]
Drained nodes put back into the queue. Investigating what may have caused this behaviour.

**Comment by kryczko** [comment]
I'm not sure if this is related but I am getting seg faults on cn125: 
```
srun: error: cn125: task 0: Segmentation fault (core dumped)
```

**Comment by SamuelLarkin** [comment]
cn125 is often flaky.

**Comment by NRCGavin** [comment]
I shouldn’t have put cn125 back in the queue.  I will set it back to drain.

**Comment by kryczko** [comment]
thanks Gavin!

**Comment by kryczko** [comment]
it looks like cn120, cn135 and cn136 have drained again.

**Comment by kryczko** [comment]
I am also getting seg faults on cn110 now: 

```srun: error: cn110: task 0: Segmentation fault (core dumped)```

**Comment by kryczko** [comment]
I think cn125 needs to be set to drain again.

**Comment by NRCGavin** [comment]
Doh, I did it again.  Cn121-cn124 were in drain state again this morning and when I resumed them I included cn125.  It is in drain again now, maybe this time I will remember that it is broken or I should just take it out of the queue or set it to down state instead of drain.

**Comment by kryczko** [comment]
a bunch have nodes have drained again, it seems to be a problem when i kill a job.

**Comment by fieldsa** [comment]
Agreed. There is a documented feature of new slurm versions that places nodes into drain state if a job has a process which does not complete in the wait time (as defined with-in slurm.conf):
* https://bugs.schedmd.com/show_bug.cgi?id=3941

While this issue is likely due to a resource being held while your job is being stopped - it is possible that we can also investigate the ```UnkillableStepTimeout``` setting in slurm.conf to increase the amount of time waited, prior to draining the nodes active for the job being stopped. Presently this value is not explicitly listed and so would use the default.
```
[admin.allan.fields@trixie ~]$ scontrol show config | grep UnkillableStepTimeout
UnkillableStepTimeout   = 60 sec
```

**Comment by kryczko** [comment]
oh okay, so the nodes are not permanently to drain then? I.e. they eventually return to idle?

**Comment by fieldsa** [comment]
Nodes which have enter to drain state, may require assistance of the NRC cluster admins to set back to idle. It does not appear as though these nodes have been marked as drain for a number of months, this ticket can be reviewed further by @NRCGavin for closure.

**Comment by ddamoursNRC** [comment]
Marking closed.
