### ISSUE TITLE
job hanging

### ISSUE THREAD

**Issue by kryczko** [ai4d-iasc/trixie#55]
I have a multi-GPU multi-node inference job that was running and then hangs on nodes: cn[104-110]

I'm not sure which node is the culprit, but one of them is causing my job to hang. I can run in debug mode and report back.

**Comment by fieldsa** [comment]
cn[104-110] are all in status idle (at this point) and did not go into drain, reviewing system logs on nodes for errors.

Mar 24 09:53:55 cn110 kernel: python[3551]: segfault at 1378 ip 00007fff859dbeff sp 00007fff3b60ce60 error 4 in libcuda.so.418.67[7fff858c5000+dec000]
Mar 24 11:11:26 cn110 kernel: python[15677]: segfault at 1378 ip 00007fff859dbeff sp 00007fff3b60ce60 error 4 in libcuda.so.418.67[7fff858c5000+dec000]
Mar 24 11:31:44 cn110 kernel: python[18851]: segfault at 1378 ip 00007fff859dbeff sp 00007fff3b60ce60 error 4 in libcuda.so.418.67[7fff858c5000+dec000]

Seems this issue is isolated to cn101.
--
Mar 24 11:31:44 cn110 kernel: python[18851]: segfault at 1378 ip 00007fff859dbeff sp 00007fff3b60ce60 error 4 in libcuda.so.418.67[7fff8
58c5000+dec000]
Mar 24 11:31:44 cn110 abrt-hook-ccpp: Process 18817 (python3.7) of user 171971032 killed by SIGSEGV - dumping core
Mar 24 11:31:48 cn110 abrt-hook-ccpp: Failed to create core_backtrace: waitpid failed: No child processes
Mar 24 11:31:48 cn110 abrt-server: Executable '/gpfs/home/ryczkok/anaconda3/bin/python3.7' doesn't belong to any package and ProcessUnpackaged is set to 'no'

Temporarily taking cn110 out of queue TrixieMain.

**Comment by fieldsa** [comment]
Node cn110 is no longer draining and has been in TrixieMain for a many months now.  This ticket can be resolved.
