### ISSUE TITLE
Armadillo 10.7

### ISSUE THREAD

**Issue by Spationaute** [ai4d-iasc/trixie#67]
Hi, I would need the latest version of armadillo to use with my C++ code in the modules. For some reason, I fail to compile the library myself with the default wheel.  

`[ 33%] Building CXX object CMakeFiles/armadillo.dir/src/wrapper1.cpp.o
In file included from /cvmfs/soft.computecanada.ca/nix/store/c9qaklf3dvjvlbky3fiakmafb1p8l106-gfortran-7.3.0/include/c++/7.3.0/bits/std_abs.h:38:0,
                 from /cvmfs/soft.computecanada.ca/nix/store/c9qaklf3dvjvlbky3fiakmafb1p8l106-gfortran-7.3.0/include/c++/7.3.0/cmath:47,
                 from /cvmfs/soft.computecanada.ca/nix/store/c9qaklf3dvjvlbky3fiakmafb1p8l106-gfortran-7.3.0/include/c++/7.3.0/complex:44,
                 from /home/admin.gabriel.stpier/bio-04a/src/armadillo-10.7.1/src/wrapper1.cpp:21:
/cvmfs/soft.computecanada.ca/nix/store/59wpzavgpf1syqd6zzgc385qkm0qrd35-glibc-2.24-dev/include/stdlib.h:471:35: error: expected initializer before ‘__attribute_alloc_size__’
      __THROW __attribute_malloc__ __attribute_alloc_size__ ((2)) __wur;
`

**Comment by fieldsa** [comment]
Current version of armadillo-10.7.2. Latest version available in CC CVMFS: 9.900.2. Latest version in EPEL (RPM): 8.600.1.

I presume you are trying to build either git master or armadillo 10.x.

Perhaps can you try to load either:
```
$ module load StdEnv/2020 gcc/9.3.0  # armadillo/9.900.2
```
prior to compiling, so that the c++ is recent enough.

Or if it doesn't work try with conda to get armadillo 10 installed and use pip for the rest of the python requirements if not found in conda:
```
$ module load miniconda3
$ conda search armadillo --channel conda-forge
```
- https://github.com/conda-forge/armadillo-feedstock
- https://www.anaconda.com/blog/using-pip-in-a-conda-environment (it suggests to use conda build if something isn't in conda yet, but you could test it with pip)

**Comment by Spationaute** [comment]
It's ok, I built it myself. Thanks for the help.

If someone need it, @fieldsa was just missing hdf5:

`$ module load StdEnv/2020 gcc/9.3.0 hdf5`

**Comment by ddamoursNRC** [comment]
Marking closed.
